services:
  postgres_db:
    image: postgres:15-alpine
    container_name: agri_postgres
    environment:
      POSTGRES_USER: agri_admin
      POSTGRES_PASSWORD: agri_root123
      POSTGRES_DB: agriculture_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "sleep 10 && pg_isready -U agri_admin -d agriculture_db || exit 1"]
      interval: 5s
      timeout: 20s
      retries: 15
      start_period: 30s
    restart: unless-stopped
    networks:
      - agri-network

  pgadmin:
    image: dpage/pgadmin4:7.4
    container_name: agri_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agri.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - agri-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: ["start-dev", "--import-realm", "--hostname-strict=false"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_db:5432/agriculture_db
      KC_DB_USERNAME: agri_admin
      KC_DB_PASSWORD: agri_root123
      KC_FEATURES: token-exchange
      KC_HOSTNAME: localhost
    ports:
      - "8181:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    networks:
      - agri-network

  app:
    build: .
    container_name: agri_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/agriculture_db
      SPRING_DATASOURCE_USERNAME: agri_admin
      SPRING_DATASOURCE_PASSWORD: agri_root123
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - agri-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  agri-network:
    driver: bridge